AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DATABASE_URL:

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: index.backendHandler
      Runtime: nodejs16.x
      Events:
        UserGet:
          Type: Api
          Properties:
            Path: /user
            Method: get
        ForksGet:
          Type: Api
          Properties:
            Path: /forks
            Method: get
        ForksPost:
          Type: Api
          Properties:
            Path: /forks
            Method: post

Outputs:
  BackendFunction:
    Description: "Backend Lambda Function ARN"
    Value: !GetAtt BackendFunction.Arn
  BackendFunctionIamRole:
    Description: "Implicit IAM Role created for backend function"
    Value: !GetAtt BackendFunctionRole.Arn
