AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DATABASE_URL:
        NODE_ENV:

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: index.backendHandler
      Runtime: nodejs16.x
      Timeout: 60
      MemorySize: 1024
      Events:
        Any:
          Type: Api
          Properties:
            Path: /{all+}
            Method: any
        GetFork:
          Type: Api
          Properties:
            Path: /api/forks/{id}
            Method: GET
        Secrets:
          Type: Api
          Properties:
            Path: /api/forks/{id}/secrets 
            Method: any
        PostAction:
          Type: Api
          Properties:
            Path: /api/forks/{id}/actions/{actionName} 
            Method: POST

Outputs:
  BackendFunction:
    Description: "Backend Lambda Function ARN"
    Value: !GetAtt BackendFunction.Arn
  BackendFunctionIamRole:
    Description: "Implicit IAM Role created for backend function"
    Value: !GetAtt BackendFunctionRole.Arn
