name: Run tests
on: push

env:
  DATABASE_URL: postgres://root:root@localhost:5432

jobs:
  backend_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: root
          POSTGRES_USER: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run migrate
        run: npm run db:migrate
        working-directory: ./backend

      - name: Run test
        run: npm run test
        working-directory: ./backend
