name: 'tf-setup-backend'

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  tf-setup-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '1'
    - name: 'Print Dependencies'
      working-directory: ./iac
      run: |
        ./print-dependencies.sh
    - name: 'Terraform Setup Backend'
      working-directory: ./iac
      timeout-minutes: 20
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_DEFAULT_OUTPUT: 'json'
        TF_VAR_appName: ${{ secrets.APP_NAME }}
      run: |
        ./tf-setup-backend.sh
