name: 'tf-up'

on:
  push:
    branches: ["master", "iac-test"]
  workflow_dispatch:
  repository_dispatch:
#    types: do-terraform-apply-aws-from-master-development
# push:
#   branches:
#     - master
#     - 'story-*'  # Push events to branches matching story-1001
#     - 'releases/**'  # Push events to branches matching refs/heads/releases/10
#   tags:
#     - v1
#     - v*   # Push events to branches matching v1, v1.1, v10
#     - v**   # Push events to branches matching version/1, v/2
#     - v1.* # Push events to tags v1.0, v1.1, and v1.9
# schedule:
#   - cron:  '0 17 * * *' # runs on every day at 5pm UTC

jobs:
  tf-up:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'iac-test'
        fetch-depth: '1'
    - name: 'Print Dependencies'
      working-directory: ./iac
      run: |
        ./print-dependencies.sh
    - name: 'Terraform Up'
      working-directory: ./iac
      timeout-minutes: 20
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_DEFAULT_OUTPUT: 'json'
        TF_VAR_APP_NAME: ${{ secrets.APP_NAME }}
      run: |
        ./tf-up.sh
