name: 'tf-up'

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  tf-up:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '1'
    - name: 'Print Dependencies'
      working-directory: ./iac
      run: |
        ./print-dependencies.sh
    - name: 'Build Backend'
      working-directory: './backend'
      run: npm run build
    - name: 'Build Frontend'
      working-directory: './frontend'
      run: |
        npm i && npm run build
    - name: 'Terraform Up'
      working-directory: ./iac
      timeout-minutes: 20
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_DEFAULT_OUTPUT: 'json'
        TF_VAR_appName: ${{ secrets.APP_NAME }}
      run: |
        ./tf-up.sh
        echo "::set-env name=DATABASE_URL::$DATABASE_URL"
    # DATABASE_URL env variable should already be populated!
    - name: 'Apply DB Migrations'
      working-directory: './backend'
      run: npm run db:deploy
